- name: Install Python 3.9 on Amazon Linux 2023
  ansible.builtin.package:
    name: python3.9
    state: present

- name: Import MySQL GPG Keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - https://repo.mysql.com/RPM-GPG-KEY-mysql
    - https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

- name: Download MySQL 8.0 Repo RPM
  ansible.builtin.get_url:
    url: https://repo.mysql.com/mysql80-community-release-el9-1.noarch.rpm 
    dest: /tmp/mysql80-release.rpm

- name: Install MySQL 8.0 Repo RPM
  ansible.builtin.package:
    name: /tmp/mysql80-release.rpm
    state: present


- name: Install MySQL Client
  ansible.builtin.package:
    name: mysql-community-client
    state: present

- name: Create .my.cnf for MySQL secure login (for ec2-user and root)
  block:
    - name: Create .my.cnf for ec2-user
      ansible.builtin.copy:
        dest: /home/ec2-user/.my.cnf
        content: |
          [client]
          user={{ db_user}}
          password={{ db_password }}
          host={{ db_host }}
        mode: '0600'
        owner: ec2-user
        group: ec2-user

    - name: Create .my.cnf for root
      ansible.builtin.copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user={{ db_user}}
          password={{ db_password }}
          host={{ db_host }}
        mode: '0600'
        owner: root
        group: root
