- name: Install Python 3.9 on Amazon Linux 2023
  ansible.builtin.package:
    name: python3.9
    state: present

- name: Import MySQL GPG Keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - https://repo.mysql.com/RPM-GPG-KEY-mysql
    - https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

- name: Download MySQL 8.0 Repo RPM
  ansible.builtin.get_url:
    url: https://repo.mysql.com/mysql80-community-release-el9-1.noarch.rpm 
    dest: /tmp/mysql80-release.rpm

- name: Install MySQL 8.0 Repo RPM
  ansible.builtin.package:
    name: /tmp/mysql80-release.rpm
    state: present


- name: Install MySQL Client
  ansible.builtin.package:
    name: mysql-community-client
    state: present

- name: Set Environment Variables for DB Host
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export DB_HOST={{ db_host }}'
    create: yes

- name: Set Environment Variables for DB User
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export DB_USER={{ db_user }}'
    create: yes

- name: Set Environment Variables for DB Password  
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export DB_PASSWORD={{ db_password }}'
    create: yes          
    